### ISSUE TITLE
Fails to work with the Preview version of the Terminal

### ISSUE THREAD

**Issue by yacoob** [fran-f/keypirinha-terminal-profiles#4]
By pure chance, I've installed the Preview version of the terminal ([this](https://github.com/microsoft/terminal/releases/tag/v1.1.1671.0) instead of [this](https://github.com/microsoft/terminal/releases/tag/v1.0.1401.0)). As a result, the plugin stopped working, as it seems to have a hardcoded path to the executable, which now resides at
`C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.1.1671.0_x64__8wekyb3d8bbwe`. Funnily enough, profile detection works fine, so you can see the entries but nothing happens once you press `Enter`.

The console log:
```
19:35:40.598 ** ERROR: Error from Terminal-Profiles.TerminalProfiles.on_execute: <class 'AttributeError'>: 'NoneType' object has no attribute 'openprofile'
Traceback (most recent call last):
  File "C:\Users\yacoob\AppData\Roaming\Keypirinha\InstalledPackages\Terminal-Profiles.keypirinha-package\TerminalProfiles.py", line 60, in on_execute
```
I'm honestly unsure what's the proper solution here - better heuristics for finding the executable would definitely work, but I have no idea how often do those paths change (including the hex string etc.).

**Comment by fran-f** [comment]
Hello, thanks for investigating this!

This plugin invokes Terminal by running the `wt.exe` shim, which *in theory* does not move. But I'm not sure what happens when the Preview is installed, I will try to reproduce this in the next days.

In the meanwhile, could you try changing the `executable` setting in Terminal-Profiles's configuration, so that it points to the Preview executable? An easy way to find it is to type "key conf term" in Keypirina 😉

**Comment by fran-f** [comment]
Hey @yacoob, any news on your issue?

**Comment by yacoob** [comment]
No, and I won't be able to test much right now - lost my windows machine access, and I'm not sure when I'll get my hands on another one. Sorry :/

**Comment by fran-f** [comment]
Sorry to hear that! I'll see if I can investigate the issue on my own 🙂

**Comment by fran-f** [comment]
Closing this as v1.5 adds support for Preview, and multiple installations.
